pipeline:
  merge:
    image: alpine
    commands:
      - apk add --no-cache alpine-sdk go
      - apk add libexosip2-dev libosip2-dev --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
      - go build ./...
      - go test ./...
    when:
      event: pull_request
